### ISSUE TITLE
Seleccionar Licencia

### ISSUE THREAD

**Issue by aasanchez** [phpdevenezuela/TelegramBot#2]
Todo proyecto Open Source, debe tener una licencia que lo respalde, y es algo tan importante como el codigo del proyecto... Asi que se deberia seleccionar que licencia se va a usar, yo propongo **Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)**

[Simplificacion para lectura de simples mortales](https://creativecommons.org/licenses/by-sa/4.0/deed.es) o [Licencia Full Texto](https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt)

**Comment by xombra** [comment]
Usualmente la CC no va relacionada con Software,.
Es preferible usar alguna de las licencias para ello:
GPL - Apache -MPL o MIT

**Comment by xombra** [comment]
Particularmente uso La licencia Apache, pero también a veces la MIT

**Comment by oyepez003** [comment]
Yo prpongo MIT a nombre de PHP de Venezuela

**Comment by aasanchez** [comment]
Sera MIT entonces...
